In [ ]:
import numpy as np

A = np.array([[56.0, 0.0,4.4,68.0],
    [1.2,104.0,52.0,8.0],
    [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = A/cal.reshape(1,4) * 100
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [9]:
a = np.random.rand(3,3)
b = np.random.rand(3,1)
c = a * b
print(c)

[[0.01369293 0.50796644 0.33585791]
 [0.53439533 0.86801151 0.89896761]
 [0.36686923 0.38963193 0.65572886]]


In [7]:
a = np.random.rand(12288,150)
b = np.random.rand(150,45)
c = np.dot(a,b)
print(c)

[[33.40295668 36.83886026 36.26671892 ... 34.56177346 30.51343314
  35.16437144]
 [35.65025814 39.42854438 40.92247294 ... 36.73656408 34.29904187
  37.54377153]
 [33.59493813 38.17932479 35.29975439 ... 31.94940937 30.69010713
  34.05810752]
 ...
 [37.13639121 38.93732943 37.61556085 ... 36.49279865 35.54326562
  37.36547922]
 [33.47416184 36.91778067 35.92079709 ... 33.98361209 30.68560366
  33.09155917]
 [36.77299022 41.33137601 39.78387613 ... 35.38986979 35.60896071
  36.92492642]]
